{% set name = "plotpy" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plotpy-{{ version }}.tar.gz
  sha256: f276d045716ede241f060b7ed3a68a6be2fb79f8e70fb1db7b6f9e595643fb12

build:
  skip: true  # [py>=400 or py2k]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - numpy
    - cython >=3.0
    - pip
  run:
    - python
    - guidata >=3.7
    - pythonqwt >=0.14
    - scipy >=1.5
    - scikit-image >=0.18
    - pillow
    - tifffile

test:
  imports:
    - plotpy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Curve and image plotting tools for Python/Qt applications
  description: |
    PlotPy is is a Python library providing efficient 2D data-plotting features for interactive computing and signal/image processing application development.
    It is part of the PlotPyStack project, aiming at providing a unified framework for creating scientific GUIs with Python and Qt.
  home: https://github.com/PlotPyStack/PlotPy
  doc_url: https://plotpy.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PierreRaybaut
